const AVAILABLE_COLUMNS = [
  'type',
  'timestamp',
  'elb',
  'client:port',
  'client',
  'backend:port',
  'backend',
  'request_processing_time',
  'backend_processing_time',
  'response_processing_time',
  'elb_status_code',
  'backend_status_code',
  'received_bytes',
  'sent_bytes',
  'request',
  'requested_resource',
  'user_agent',
  'total_time',
  'count',
  'target_group_arn',
  'trace_id',
  'ssl_cipher',
  'ssl_protocol',
  'requested_resource.pathname',
  'requested_resource.host',
  'requested_resource.protocol',
  'requested_resource.port',
  'requested_resource.hostname',
  'requested_resource.path',
  'requested_resource.origin',
  'requested_resource.search',
  'requested_resource.href',
  'requested_resource.hash',
  'requested_resource.searchParams',
  'requested_resource.username',
  'requested_resource.password',
]

export const validateColumns = (columns: string[]): boolean =>
  columns.some((column) => AVAILABLE_COLUMNS.indexOf(column) > -1)
